#===-- Makefile.config - Local configuration for LLVM ------*- makefile -*--====
#
# This file is included by Makefile.common.  It defines paths and other
# values specific to a particular installation of LLVM.
#===-----------------------------------------------------------------------====

# Current working directory, used below

# Path to directory where object files should be stored during a build.
# Set LLVM_OBJ_DIR to "." if you do not want to use a separate place for
# object files.
# 
# LLVM_OBJ_DIR = .
LLVM_OBJ_DIR = /shared/$(shell whoami)

# Path to executable for Burg
# 
BURG = /home/vadve/vadve/Research/DynOpt/Burg/burg

# Path to location for purify
# 
PURIFY = /usr/dcs/applications/purify/bin/purify

# Path to location for LLVM front-end
# 
LLVMGCCDIR = /home/vadve/lattner/cvs/gcc_install
