#===-- Makefile.config - Local configuration for LLVM ------*- makefile -*--====
#
# This file is included by Makefile.common.  It defines paths and other
# values specific to a particular installation of LLVM.
#===-----------------------------------------------------------------------====

# Path to the C++ compiler to use.  This is an optional setting, which defaults
# to whatever your gmake defaults to.
#
# Under Linux, for some reason the compiler driver wants to search the PATH to
# find the system assembler, which breaks if the LLVM assembler is in our path.
# Hack it to use the assembler in /usr/bin directly.
#
CXX = PATH=/usr/bin /usr/dcs/software/evaluation/bin/g++

# We have the same problem with the CC binary, which use used by testcases for
# native builds.
#
CC := PATH=/usr/bin /usr/dcs/software/evaluation/bin/gcc

# Path to directory where object files should be stored during a build.
# Set LLVM_OBJ_DIR to "." if you do not want to use a separate place for
# object files.
# 
#LLVM_OBJ_DIR = .
LLVM_OBJ_DIR = /localhome/$(shell whoami)

# Path to location for LLVM front-end this should only be specified here if you
# want to override the value set in Makefile.$(uname)
#
#LLVMGCCDIR := /home/vadve/lattner/cvs/gcc_install_x86

# Path to location for purify, this is only needed if you build with
# ENABLE_PURIFY=1
# 
PURIFY = /usr/dcs/applications/purify/bin/purify

