#===-- Makefile.config - Local configuration for LLVM ------*- makefile -*--====
#
# This file is included by Makefile.common.  It defines paths and other
# values specific to a particular installation of LLVM.
#===-----------------------------------------------------------------------====

# Current working directory, used below

# Path to directory where object files should be stored during a build.
# Set LLVM_OBJ_DIR to "." if you do not want to use a separate place for
# object files.
# 
#LLVM_OBJ_DIR = .
LLVM_OBJ_DIR = /localhome/$(shell whoami)

# Path to executable for Burg
# 
BURG = $(LEVEL)/utils/Burg/burg

# Path to location for purify
# 
PURIFY = /usr/dcs/applications/purify/bin/purify

# Path to location for LLVM front-end
# 
LLVMGCCDIR = /home/vadve/lattner/cvs/gcc_install

# Path to the C++ compiler to use.  Under linux, for some reason the compiler
# driver wants to search the PATH to find the system assembler, which breaks if
# the LLVM assembler is in our path.  Hack it to use the assembler in /usr/bin
# directly.
#
CXX = PATH=/usr/bin /usr/dcs/software/evaluation/bin/g++
