##===- examples/OCaml-Kaleidoscope/Chapter2/Makefile -------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
# 
# This is the makefile for the Objective Caml kaleidoscope tutorial, chapter 2.
# 
##===----------------------------------------------------------------------===##

LEVEL := ../../..
TOOLNAME := OCaml-Kaleidoscope-Ch2
EXAMPLE_TOOL := 1
UsedComponents := core
UsedOcamLibs := llvm

OCAMLCFLAGS += -pp camlp4of

include $(LEVEL)/bindings/ocaml/Makefile.ocaml
