##===- runtime/GC/Makefile ---------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
PARALLEL_DIRS := SemiSpace
EXTRA_DIST := gc_exported_symbols.lst
include $(LEVEL)/Makefile.common

# Install target for libraries: Copy into $LLVMGCCDIR/bytecode-libs
#
install::

clean::
