##===- tools/lli/Makefile ------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL := ../../..
TOOLNAME := merge-fdata

include $(LEVEL)/Makefile.config

LINK_COMPONENTS := support

SOURCES := merge-fdata.cpp ../DataReader.cpp

include $(LLVM_SRC_ROOT)/Makefile.rules
