from typing import List

globals: _Globals

class _Globals:
    dialect_search_modules: List[str]
    def __init__(self, *args, **kwargs) -> None: ...
    def _register_dialect_impl(self, dialect_namespace: str, dialect_class: object) -> None: ...
    def _register_operation_impl(self, operation_name: str, operation_class: object, raw_opview_class: object) -> None: ...
    def append_dialect_search_prefix(self, module_name: str) -> None: ...

def register_dialect(dialect_class: object) -> object: ...
def register_operation(dialect_class: object) -> object: ...
