##===- tools/llvm2cpp/Makefile -----------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = llvm2cpp
LINK_COMPONENTS = bitreader

include $(LEVEL)/Makefile.common

CompileCommonOpts := $(CompileCommonOpts) -Wno-format 
