##===- examples/ParallelJIT/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by Reid A. Spencer and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = ParallelJIT
EXAMPLE_TOOL = 1

# Enable JIT support
LLVMLIBS := JIT

include $(LEVEL)/Makefile.common

LIBS += -lpthread
