compilation_unit {
  declarations {
    class_declaration {
      members {
        function {
          return_term {
            kind: Auto
          }
          body {
            statements {
              await_statement {
              }
            }
          }
        }
      }
    }
  }
}
