compilation_unit {
  package_statement {
    package_name: "ExplorerTest"
  }
  is_api: true
  declarations {
    interface {
      name: "Vector"
      members {
        function {
          name: "Zero"
          param_pattern {
          }
          return_term {
            kind: Expression
            type {
              identifier {
                name: "Self"
              }
            }
          }
        }
      }
      members {
        function {
          name: "Add"
          me_pattern {
            name: "me"
            type {
              expression_pattern {
                expression {
                  identifier {
                    name: "Self"
                  }
                }
              }
            }
          }
          param_pattern {
            fields {
              binding_pattern {
                name: "b"
                type {
                  expression_pattern {
                    expression {
                      identifier {
                        name: "Self"
                      }
                    }
                  }
                }
              }
            }
          }
          return_term {
            kind: Expression
            type {
              identifier {
                name: "Self"
              }
            }
          }
        }
      }
      members {
        function {
          name: "Scale"
          me_pattern {
            name: "me"
            type {
              expression_pattern {
                expression {
                  identifier {
                    name: "Self"
                  }
                }
              }
            }
          }
          param_pattern {
            fields {
              binding_pattern {
                name: "v"
                type {
                  expression_pattern {
                    expression {
                      int_type_literal {
                      }
                    }
                  }
                }
              }
            }
          }
          return_term {
            kind: Expression
            type {
              identifier {
                name: "Self"
              }
            }
          }
        }
      }
      self {
        name: "Self"
        type {
          type_type_literal {
          }
        }
      }
    }
  }
  declarations {
    class_declaration {
      name: "Point"
      members {
        variable {
          binding {
            name: "x"
            type {
              expression_pattern {
                expression {
                  int_type_literal {
                  }
                }
              }
            }
          }
        }
      }
      members {
        variable {
          binding {
            name: "y"
            type {
              expression_pattern {
                expression {
                  int_type_literal {
                  }
                }
              }
            }
          }
        }
      }
      members {
        impl {
          kind: InternalImpl
          impl_type {
            identifier {
              name: "Self"
            }
          }
          interface {
            identifier {
              name: "Vector"
            }
          }
          members {
            function {
              name: "Zero"
              param_pattern {
              }
              return_term {
                kind: Expression
                type {
                  identifier {
                    name: "Self"
                  }
                }
              }
              body {
                statements {
                  return_statement {
                    expression {
                      struct_literal {
                        fields {
                          name: "x"
                          expression {
                            int_literal {
                              value: 0
                            }
                          }
                        }
                        fields {
                          name: "y"
                          expression {
                            int_literal {
                              value: 0
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          members {
            function {
              name: "Add"
              me_pattern {
                name: "me"
                type {
                  expression_pattern {
                    expression {
                      identifier {
                        name: "Self"
                      }
                    }
                  }
                }
              }
              param_pattern {
                fields {
                  binding_pattern {
                    name: "b"
                    type {
                      expression_pattern {
                        expression {
                          identifier {
                            name: "Self"
                          }
                        }
                      }
                    }
                  }
                }
              }
              return_term {
                kind: Expression
                type {
                  identifier {
                    name: "Self"
                  }
                }
              }
              body {
                statements {
                  return_statement {
                    expression {
                      struct_literal {
                        fields {
                          name: "x"
                          expression {
                            primitive_operator {
                              op: Add
                              arguments {
                                field_access {
                                  field: "x"
                                  aggregate {
                                    identifier {
                                      name: "me"
                                    }
                                  }
                                }
                              }
                              arguments {
                                field_access {
                                  field: "x"
                                  aggregate {
                                    identifier {
                                      name: "b"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                        fields {
                          name: "y"
                          expression {
                            primitive_operator {
                              op: Add
                              arguments {
                                field_access {
                                  field: "y"
                                  aggregate {
                                    identifier {
                                      name: "me"
                                    }
                                  }
                                }
                              }
                              arguments {
                                field_access {
                                  field: "y"
                                  aggregate {
                                    identifier {
                                      name: "b"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          members {
            function {
              name: "Scale"
              me_pattern {
                name: "me"
                type {
                  expression_pattern {
                    expression {
                      identifier {
                        name: "Self"
                      }
                    }
                  }
                }
              }
              param_pattern {
                fields {
                  binding_pattern {
                    name: "v"
                    type {
                      expression_pattern {
                        expression {
                          int_type_literal {
                          }
                        }
                      }
                    }
                  }
                }
              }
              return_term {
                kind: Expression
                type {
                  identifier {
                    name: "Self"
                  }
                }
              }
              body {
                statements {
                  return_statement {
                    expression {
                      struct_literal {
                        fields {
                          name: "x"
                          expression {
                            primitive_operator {
                              op: Mul
                              arguments {
                                field_access {
                                  field: "x"
                                  aggregate {
                                    identifier {
                                      name: "me"
                                    }
                                  }
                                }
                              }
                              arguments {
                                identifier {
                                  name: "v"
                                }
                              }
                            }
                          }
                        }
                        fields {
                          name: "y"
                          expression {
                            primitive_operator {
                              op: Mul
                              arguments {
                                field_access {
                                  field: "y"
                                  aggregate {
                                    identifier {
                                      name: "me"
                                    }
                                  }
                                }
                              }
                              arguments {
                                identifier {
                                  name: "v"
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  declarations {
    function {
      name: "AddAndScaleGeneric"
      deduced_parameters {
        name: "T"
        type {
          identifier {
            name: "Vector"
          }
        }
      }
      param_pattern {
        fields {
          binding_pattern {
            name: "a"
            type {
              expression_pattern {
                expression {
                  identifier {
                    name: "T"
                  }
                }
              }
            }
          }
        }
        fields {
          binding_pattern {
            name: "s"
            type {
              expression_pattern {
                expression {
                  int_type_literal {
                  }
                }
              }
            }
          }
        }
      }
      return_term {
        kind: Expression
        type {
          identifier {
            name: "T"
          }
        }
      }
      body {
        statements {
          return_statement {
            expression {
              call {
                function {
                  field_access {
                    field: "Scale"
                    aggregate {
                      call {
                        function {
                          field_access {
                            field: "Add"
                            aggregate {
                              identifier {
                                name: "a"
                              }
                            }
                          }
                        }
                        argument {
                          tuple_literal {
                            fields {
                              call {
                                function {
                                  field_access {
                                    field: "Zero"
                                    aggregate {
                                      identifier {
                                        name: "T"
                                      }
                                    }
                                  }
                                }
                                argument {
                                  tuple_literal {
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
                argument {
                  tuple_literal {
                    fields {
                      identifier {
                        name: "s"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  declarations {
    function {
      name: "Main"
      param_pattern {
      }
      return_term {
        kind: Expression
        type {
          int_type_literal {
          }
        }
      }
      body {
        statements {
          variable_definition {
            pattern {
              binding_pattern {
                name: "a"
                type {
                  expression_pattern {
                    expression {
                      identifier {
                        name: "Point"
                      }
                    }
                  }
                }
              }
            }
            init {
              struct_literal {
                fields {
                  name: "x"
                  expression {
                    int_literal {
                      value: 2
                    }
                  }
                }
                fields {
                  name: "y"
                  expression {
                    int_literal {
                      value: 1
                    }
                  }
                }
              }
            }
          }
        }
        statements {
          variable_definition {
            pattern {
              binding_pattern {
                name: "p"
                type {
                  expression_pattern {
                    expression {
                      identifier {
                        name: "Point"
                      }
                    }
                  }
                }
              }
            }
            init {
              call {
                function {
                  identifier {
                    name: "AddAndScaleGeneric"
                  }
                }
                argument {
                  tuple_literal {
                    fields {
                      identifier {
                        name: "a"
                      }
                    }
                    fields {
                      int_literal {
                        value: 5
                      }
                    }
                  }
                }
              }
            }
          }
        }
        statements {
          return_statement {
            expression {
              primitive_operator {
                op: Sub
                arguments {
                  field_access {
                    field: "x"
                    aggregate {
                      identifier {
                        name: "p"
                      }
                    }
                  }
                }
                arguments {
                  int_literal {
                    value: 10
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
