compilation_unit {
  declarations {
    choice {
      alternatives {
        signature {
          primitive_operator {
            arguments {
              intrinsic {
                argument {
                  fields {
                    primitive_operator {
                      arguments {
                        identifier {
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
