LEVEL = ../..

TOOLNAME = gccas
USEDLIBS = asmparser bcwriter transforms ipo scalaropts analysis \
           target.a transformutils ipa datastructure vmcore support.a

include $(LEVEL)/Makefile.common
