##===- tools/gccas/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

TOOLNAME = gccas
USEDLIBS = asmparser bcwriter transforms ipo.a ipa.a scalaropts analysis.a \
           target.a transformutils vmcore support.a

include $(LEVEL)/Makefile.common
