##===- lib/Support/bzip2/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..
LIBRARYNAME = LLVMbzip2
SOURCES = blocksort.c huffman.c crctable.c randtable.c compress.c decompress.c \
	  bzlib.c
EXTRA_DIST = bzlib.h bzlib_private.h CHANGES LICENSE README \
	     README.COMPILATION.PROBLEMS Y2K_INFO

include $(LEVEL)/Makefile.common
