##===- tools/gccld/Makefile --------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..

TOOLNAME = gccld
LINK_COMPONENTS = bcreader bcwriter ipo scalaropts ipa linker
REQUIRES_EH := 1

include $(LEVEL)/Makefile.common
