LEVEL = ../..

TOOLNAME = gccld
USEDLIBS = ipo.a analysis.a transforms.a ipa.a scalaropts.a transformutils.a \
           target.a bcreader bcwriter vmcore support.a

include $(LEVEL)/Makefile.common
