# To build the docs site, first install the mkdocs dependencies:
# $ pip install mkdocs mkdocs-simple-hooks mkdocs-material
# Then `mkdocs serve` to run the site locally.

site_name: Carbon Language
theme:
  name: material
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_page_content: "docs.hooks:on_page_content"
