##===- lib/Debugger/Makefile -------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
LIBRARYNAME = LLVMDebugger
EXTRA_DIST = README.txt
REQUIRES_EH := 1
BUILD_ARCHIVE = 1

include $(LEVEL)/Makefile.common
