##===- lld/lib/ReaderWriter/Native/Makefile --------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LLD_LEVEL := ../../..
LIBRARYNAME := lldNative
USEDLIBS = lldCore.a

include $(LLD_LEVEL)/Makefile
