##===- tools/llvm-bcanalyzer/Makefile ----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by Reid Spencer and is distributed under the 
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..

TOOLNAME = llvm-bcanalyzer
USEDLIBS = bcreader vmcore support.a
include $(LEVEL)/Makefile.common
