##===- lib/System/Makefile ---------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by Reid Spencer and is distributed under the 
# University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..
LIBRARYNAME = LLVMSystem
BUILD_ARCHIVE = 1

EXTRA_DIST = Unix Win32

include $(LEVEL)/Makefile.common
