##===- tools/Makefile --------------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LLD_LEVEL := ..
LEVEL := $(LLD_LEVEL)/../..

include $(LLD_LEVEL)/../../Makefile.config

PARALLEL_DIRS := linker-script-test lld

include $(LLD_LEVEL)/Makefile
