#!/usr/bin/env bash

echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
echo "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//ENhttp://www.apple.com/DTDs/PropertyList-1.0.dtd\">"
echo "<plist version=\"1.0\">"
echo "<dict>"
echo "    <key>93483F20-FD9C-30AD-A72D-94EF12837DBA</key>"
echo "    <dict>"
echo "        <key>DBGArchitecture</key>"
echo "        <string>arm64</string>"
echo "        <key>DBGError</key>"
echo "        <string>UUID information was not found</string>"
echo "    </dict>"
echo "</dict>"
echo "</plist>"
