##===- source/Plugins/Process/Linux/Makefile ---------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LLDB_LEVEL := ../../../..
LIBRARYNAME := lldbPluginProcessLinux
BUILD_ARCHIVE = 1

# Extend the include path so we may locate UnwindLLDB.h
CPPFLAGS += -I $(LLDB_LEVEL)/source/Plugins/Utility

include $(LLDB_LEVEL)/Makefile
