##===- tools/Makefile --------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ..
PARALLEL_DIRS := llvm-config opt llvm-as llvm-dis llc llvm-bcanalyzer \
                 llvm-extract lli llvm-db llvm-ar llvm-ld llvm-prof llvm-nm \
                 gccas llvm-ranlib llvm-stub gccld llvm2cpp \
                 bugpoint llvmc llvm-link

include $(LEVEL)/Makefile.common
