##===- tools/Makefile --------------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL := ..
PARALLEL_DIRS := llvm-config llvm-as llvm-dis opt gccas llc llvm-link lli gccld\
                 llvm-stub llvm-extract llvm-nm llvm-prof llvm-ar llvm-ranlib \
		 llvm-bcanalyzer llvmc llvm-ld llvm-db bugpoint llvm2cpp

include $(LEVEL)/Makefile.common
