##===- unittests/AST/Makefile ------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

CLANG_LEVEL = ../..
TESTNAME = AST
LINK_COMPONENTS := support mc
USEDLIBS = clangAST.a clangBasic.a

include $(CLANG_LEVEL)/unittests/Makefile
