FIND_PATH(OPENSCOP_INCLUDE_DIR openscop/scop.h)

FIND_LIBRARY(OPENSCOP_LIBRARY NAMES openscop)

IF (OPENSCOP_INCLUDE_DIR AND OPENSCOP_LIBRARY)
  SET(OPENSCOP_FOUND TRUE)
ENDIF (OPENSCOP_INCLUDE_DIR AND OPENSCOP_LIBRARY)


IF (OPENSCOP_FOUND)
  IF (NOT Isl_FIND_QUIETLY)
    MESSAGE(STATUS "Found OpenScop: ${OPENSCOP_LIBRARY}")
  ENDIF (NOT Isl_FIND_QUIETLY)
ELSE (OPENSCOP_FOUND)
  IF (Isl_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OpenScop")
  ENDIF (Isl_FIND_REQUIRED)
ENDIF (OPENSCOP_FOUND)

