FIND_PATH(SCOPLIB_INCLUDE_DIR scoplib/scop.h)

FIND_LIBRARY(SCOPLIB_LIBRARY NAMES scoplib)

IF (SCOPLIB_INCLUDE_DIR AND SCOPLIB_LIBRARY)
  SET(SCOPLIB_FOUND TRUE)
ENDIF (SCOPLIB_INCLUDE_DIR AND SCOPLIB_LIBRARY)


IF (SCOPLIB_FOUND)
  IF (NOT Isl_FIND_QUIETLY)
    MESSAGE(STATUS "Found SCoPLib: ${SCOPLIB_LIBRARY}")
  ENDIF (NOT Isl_FIND_QUIETLY)
ELSE (SCOPLIB_FOUND)
  IF (Isl_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SCoPLib")
  ENDIF (Isl_FIND_REQUIRED)
ENDIF (SCOPLIB_FOUND)

