# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Toolchain bug
description: >
  Report a bug with the toolchain.
labels: explorer
body:
  - type: markdown
    attributes:
      value: >
        **Attention:** If this is a _question_, please use either [GitHub
        Discussions](https://github.com/carbon-language/carbon-lang/discussions)
        or [Discord](https://discord.gg/ZjVdShJDAs).
  - type: textarea
    id: desc
    attributes:
      label: >
        Description of the bug:
  - type: textarea
    id: repro
    attributes:
      label: >
        What's the simplest, easiest way to reproduce this bug?
      description: >
        Please provide example code and errors; a shortlink to the execution on
        carbon.compiler-explorer.com can also help.
  - type: textarea
    id: extras
    attributes:
      label: >
        Any other information, logs, or outputs that you want to share?
