##===- projects/Stacker/Makefile ---------------------------*- Makefile -*-===##
#
# This is the Stacker top-level Makefile
#
##===----------------------------------------------------------------------===##

LEVEL = .
DIRS = lib tools samples 
EXTRA_DIST = test

include $(LEVEL)/Makefile.common
