##===- projects/Stacker/Makefile ---------------------------*- Makefile -*-===##
#
# This is the Stacker top-level Makefile
#
##===----------------------------------------------------------------------===##

LEVEL = .
DIRS = lib tools
EXTRA_DIST = test samples

include $(LEVEL)/Makefile.common
