##===- projects/Stacker/Makefile ---------------------------*- Makefile -*-===##
#
# This is the Stacker top-level Makefile
#
##===----------------------------------------------------------------------===##

LEVEL = .
DIRS = lib tools

include $(LEVEL)/Makefile.common
