##===- tools/lli/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL    := ../..
TOOLNAME := lli
LLVMLIBS := JIT

# Enable JIT support
include $(LEVEL)/Makefile.common
