##===- tools/lli/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL    := ../..
TOOLNAME := lli
LINK_COMPONENTS := jit interpreter nativecodegen bitreader asmparser selectiondag

# Enable JIT support
include $(LEVEL)/Makefile.common
