##===- tools/llvmc2/Makefile -------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open
# Source License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..

BUILTIN_PLUGINS = Base
DRIVER_NAME = llvmc2
DIRS = plugins core

export BUILTIN_PLUGINS
export DRIVER_NAME

include $(LEVEL)/Makefile.common
