##===- projects/Stacker/tools/Makefile ---------------------*- Makefile -*-===##
#
# This is the stacker tools makefile
#
##===----------------------------------------------------------------------===##

#
# Indicates our relative path to the top of the project's root directory.
#
LEVEL = ../../..

#
# Directories that needs to be built.
#
DIRS = stkrc

#
# Include the Master Makefile that knows how to build all.
#
include $(LEVEL)/Makefile.common
