# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# The prelude, and all of its dependencies.
filegroup(
    name = "prelude",
    data = ["prelude.carbon"] + glob(["prelude/**/*.carbon"]),
    visibility = ["//visibility:public"],
)
