##===- tools/llvm-ranlib/Makefile --------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by the LLVM research group and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
TOOLNAME = llvm-ranlib
LINK_COMPONENTS = archive
REQUIRES_EH := 1

include $(LEVEL)/Makefile.common
