set(CMAKE_BUILD_TYPE RelWithDebInfo CACHE STRING "")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON CACHE BOOL "")

set(LLVM_TARGETS_TO_BUILD X86;ARM;AArch64 CACHE STRING "")
set(LLVM_ENABLE_ASSERTIONS ON CACHE BOOL "")
set(LLVM_ENABLE_MODULES ON CACHE BOOL "")

set(LIBCXX_ENABLE_SHARED OFF CACHE BOOL "")
set(LIBCXX_ENABLE_STATIC OFF CACHE BOOL "")

# Release builds set these explicitly:
#set(LLDB_VERSION_MAJOR 9999 CACHE STRING "")
#set(LLDB_VERSION_MINOR 9 CACHE STRING "")
#set(LLDB_VERSION_PATCH 9 CACHE STRING "")
#set(LLDB_VERSION_SUFFIX git CACHE STRING "")
