##===- tools/llvm-db/Makefile ------------------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##

LEVEL = ../..
TOOLNAME = llvm-db
LINK_COMPONENTS := debugger
REQUIRES_EH := 1

include $(LEVEL)/Makefile.common
