=pod

=head1 NAME

llvm-stress - generate random .ll files

=head1 SYNOPSIS

B<llvm-cov> [-gcno=filename] [-gcda=filename] [dump]

=head1 DESCRIPTION

The B<llvm-stress> tool is used to generate random .ll files that can be used to
test different components of LLVM.

=head1 OPTIONS

=over

=item B<-o> I<filename>

Specify the output filename.

=item B<-size> I<size>

Specify the size of the generated .ll file.

=item B<-seed> I<seed>

Specify the seed to be used for the randomly generated instructions.

=back

=head1 EXIT STATUS

B<llvm-stress> returns 0.

=head1 AUTHOR

B<llvm-stress> is maintained by the LLVM Team (L<http://llvm.org/>).

=cut
