if(NOT CMAKE_LLAsm_COMPILE_OBJECT)
  set(CMAKE_LLAsm_COMPILE_OBJECT
	  "${CMAKE_LLAsm_PREPROCESSOR} -E -P  <DEFINES> <INCLUDES> <FLAGS> -x cl  <SOURCE> -o - | <CMAKE_LLAsm_COMPILER> -o <OBJECT> ")
endif()

if(NOT CMAKE_LLAsm_CREATE_STATIC_LIBRARY)
  set(CMAKE_LLAsm_CREATE_STATIC_LIBRARY
    "<CMAKE_LLAsm_ARCHIVE> <LINK_FLAGS> -o <TARGET> <OBJECTS>")
endif()

set(CMAKE_INCLUDE_FLAG_LLAsm "-I")
