if(NOT CMAKE_CLC_COMPILE_OBJECT)
  set(CMAKE_CLC_COMPILE_OBJECT
    "<CMAKE_CLC_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT> -c <SOURCE> -emit-llvm")
endif()

if(NOT CMAKE_CLC_CREATE_STATIC_LIBRARY)
  set(CMAKE_CLC_CREATE_STATIC_LIBRARY
    "<CMAKE_CLC_ARCHIVE> -o <TARGET> <OBJECTS>")
endif()

set(CMAKE_INCLUDE_FLAG_CLC "-I")
