##===- examples/Kaleidoscope/Chapter2/Makefile -------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../../..
TOOLNAME = Kaleidoscope-Ch2
EXAMPLE_TOOL = 1

LLVM_CXXFLAGS := -Wno-unused-private-field

include $(LEVEL)/Makefile.common
