##===- Source/Plugins/LangRuntime/RenderScript/RenderScriptRuntime/Makefile ----*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LLDB_LEVEL := ../../../../..
LIBRARYNAME := lldbPluginRenderScriptRuntime
BUILD_ARCHIVE = 1

include $(LLDB_LEVEL)/Makefile
