##===- utils/fpcmp/Makefile --------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TOOLNAME = fpcmp
USEDLIBS = LLVMSupport.a
NO_INSTALL = 1

include $(LEVEL)/Makefile.common

