LEVEL = ../../..
DIRS  = ADCE \
	ConstProp \
	ConstantMerge \
	CorrelatedExprs \
	DecomposeMultiDimRefs \
	FunctionResolve \
	GCSE \
	GlobalDCE \
	IndVarsSimplify \
	Inline \
	InstCombine \
	LevelRaise \
	LICM \
	LowerSwitch \
	Mem2Reg \
	PiNodeInserter \
	PRE \
	LoopPreheaders \
	ProfilePaths \
	Reassociate \
	SCCP \
	ScalarRepl \
	SimplifyCFG \
	TailDup

include $(LEVEL)/Makefile.common
