LEVEL  = ../../..
DIRS   = ADCE CFGSimplify ConstProp CorrelatedExprs DecomposeMultiDimRefs \
	 FunctionResolve GCSE \
	 GlobalDCE IndVarSimplify Inline InstCombine LevelRaise LICM Mem2Reg \
	 PiNodeInserter ProfilePaths Reassociate SCCP SimplifyCFG
include $(LEVEL)/Makefile.common
