#!/bin/bash

if [ -n "`git status -uno -s --porcelain`" ]; then
    echo "You have unstashed changes. Can not update repository..."
    git status -uno
    exit 1
fi

git fetch
OLD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
git checkout master 2> /dev/null
git svn rebase -l
git checkout $OLD_BRANCH 2> /dev/null

exit 0
