LEVEL = ../..
TOOLNAME = llc
USEDLIBS = mapping sparc target.a regalloc sched select preselect target.a \
           instrument livevar bcreader bcwriter ipo ipa.a datastructure.a \
	   scalaropts transforms analysis transformutils vmcore support
TOOLLINKOPTS = -ldl

include $(LEVEL)/Makefile.common

