LEVEL = ../..
TOOLNAME = llc
USEDLIBS = sparc regalloc sched select target \
           instrument livevar bcreader bcwriter analysis transforms analysis \
	   scalaropts vmcore support

include $(LEVEL)/Makefile.common

