##===- examples/ExceptionDemo/Makefile --------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
# 
##===---------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = ExceptionDemo
EXAMPLE_TOOL = 1
REQUIRES_EH = 1

LINK_COMPONENTS := jit interpreter nativecodegen

include $(LEVEL)/Makefile.common
