# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

repository: carbon-language/carbon-lang
topnav_title: Carbon
site_title: Carbon language
url: 'https://carbon-lang.dev/'

source: ./site
destination: /tmp/jekyll_site
markdown: CommonMarkGhPages

exclude:
  - src/

include:
  - '*.md'
  - '.pre-commit-config.yaml'
  - '.prettierrc.yaml'

feedback_disable: true

sidebars:
  - sidebar

defaults:
  - values:
      layout: 'page'
      search: true
      topnav: topnav

# Settings from https://github.com/github/jekyll-commonmark-ghpages.
commonmark:
  options: ['SMART', 'FOOTNOTES']
  extensions: ['strikethrough', 'autolink', 'table', 'tagfilter']
