##===- unittests/DebugInfo/Makefile ------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = CodeGen
LINK_COMPONENTS := asmprinter codegen support

include $(LEVEL)/Makefile.config

include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
