##===- unittests/ExecutionEngine/Makefile ------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../..
TESTNAME = ExecutionEngine
LINK_COMPONENTS := engine interpreter

include $(LEVEL)/Makefile.config

PARALLEL_DIRS = JIT

include $(LLVM_SRC_ROOT)/unittests/Makefile.unittest
