LEVEL = ../..
TOOLNAME = opt

USEDLIBS = bcreader bcwriter instrument profpaths \
           sparc mapping regalloc.a sched select codegen preopts \
           postopts.a livevar scalaropts \
           ipo ipa.a datastructure transforms target.a analysis \
           transformutils vmcore support

TOOLLINKOPTS = -ldl

include $(LEVEL)/Makefile.common
