LEVEL = ../..
TOOLNAME = opt

USEDLIBS = bcreader bcwriter instrument profpaths scalaropts \
           ipo ipa.a datastructure.a transforms target.a analysis \
           transformutils vmcore support
TOOLLINKOPTS = -ldl

include $(LEVEL)/Makefile.common

