#!/usr/bin/python

import os
import sys
from ccclib import Arguments
from ccclib import Driver
        
def main():
    progDir = os.path.dirname(sys.argv[0])
    progName = os.path.basename(sys.argv[0])

    d = Driver.Driver(progDir, progName)
    try:
        d.run(sys.argv[1:])
    except Arguments.InvalidArgumentsError,e:
        print >>sys.stderr, "%s: %s" % (progName, e.args[0])
        sys.exit(1)
    except Arguments.MissingArgumentError,e:
        print >>sys.stderr, "%s: %s" % (progName, e.args[0])
        sys.exit(1)
    except NotImplementedError,e:
        print >>sys.stderr, "%s: not implemented: %s" % (progName, e.args[0])

if __name__=='__main__':
    main()
