##===- projects/HowToUseJIT/Makefile -----------------------*- Makefile -*-===##
# 
#                     The LLVM Compiler Infrastructure
#
# This file was developed by Valery A. Khamenya and is distributed under
# the University of Illinois Open Source License. See LICENSE.TXT for details.
# 
##===----------------------------------------------------------------------===##
LEVEL = ../..
TOOLNAME = Fibonacci
USEDLIBS = lli-jit lli-interpreter codegen executionengine x86 selectiondag \
	   scalaropts analysis.a transformutils.a bcreader target.a vmcore \
	   support.a

include $(LEVEL)/Makefile.common
