##-----------------------------------------------------------*-Makefile-*-
## Common rules for generating, linking, and compiling via LLVM.  This is
## used to implement a robust testing framework for LLVM
##------------------------------------------------------------------------

## NOTE: This is preliminary and will change in the future


include ${LEVEL}/Makefile.common

.PHONY: clean default

# These files, which might be intermediate results, should not be deleted by
# make
.PRECIOUS: Output/%.bc  Output/%.ll
.PRECIOUS: Output/%.tbc Output/%.tll
.PRECIOUS: Output/.dir

# LLVM Tool Definitions...
#
LCC      = /home/vadve/lattner/cvs/gcc_install/bin/gcc
LCC1     = /home/vadve/lattner/cvs/gcc_install/lib/gcc-lib/llvm/3.1/cc1
TOOLS    = $(LEVEL)/tools/Debug
LLI      = $(TOOLS)/lli
LLC      = $(TOOLS)/llc
LAS      = $(TOOLS)/as
LGCCAS   = $(TOOLS)/gccas
LDIS     = $(TOOLS)/dis 
LOPT     = $(TOOLS)/opt
LLINK    = $(TOOLS)/link

LCCFLAGS  += -O2 -Wall
LLCFLAGS =
FAILURE  = $(LEVEL)/test/Failure.sh

# Native Tool Definitions
NATGCC  = /usr/dcs/software/supported/bin/gcc
CC      = /opt/SUNWspro/bin/cc
AS	= /opt/SUNWspro/bin/cc
DIS     = /usr/ccs/bin/dis
CP	= /bin/cp -f
CFLAGS  += -g -xarch=v9

LLCLIB   = $(LEVEL)/test/runtime.o
LIBS    += $(LLCLIB)



ifeq ($(TRACE), yes)
    LLCFLAGS += -trace
endif
ifeq ($(TRACEM), yes)
    LLCFLAGS += -tracem
endif

clean ::
	$(RM) a.out core
	$(RM) -rf Output/

Output/%.ll: %.c $(LCC1) Output/.dir
	$(LCC) $(LCCFLAGS) -S $< -o $@

Output/%.bc: Output/%.ll $(LGCCAS)
	$(LGCCAS) $< -o $@

Output/%.bc: %.ll $(LAS)
	$(LAS) $< -o $@

#
# Testing versions of provided utilities...
#
Output/%.tll: %.c $(LCC1) Output/.dir
	@echo "======== Compiling $<"
	$(LCC) $(LCCFLAGS) -S $< -o $@ || \
	    ( rm -f $@; $(FAILURE) $@ )

Output/%.tbc: Output/%.tll $(LAS)
	@echo "======== Assembling $<"
	$(LAS) -f $< -o $@ || \
            ( rm -f $@; $(FAILURE) $@ )



#%.s: %.linked.bc
#	$(LLC) -f $(LLCFLAGS) $< -o $@

#%: %.o $(LIBS)
#	$(CC) $(LDFLAGS) $< $(LIBS) -o $@


## Cancel built-in implicit rules that override above rules
%: %.s

%: %.c

%.o: %.c

## The next two rules are for disassembling an executable or an object file
#%.dis: %
#	$(DIS) $< > $@

#%.dis: %.o
#	$(DIS) $< > $@


