##===- lld/lib/ReaderWriter/PECOFF/Makefile --------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LLD_LEVEL := ../../..
LIBRARYNAME := lldPECOFF
USEDLIBS = lldReaderWriter.a lldCore.a

include $(LLD_LEVEL)/Makefile
