##===- tools/lli/Makefile ------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL := ../../..
TOOLNAME := lli-child-target

include $(LEVEL)/Makefile.config

LINK_COMPONENTS := support

CXXFLAGS += -DLLI_BUILDING_CHILD

SOURCES := ChildTarget.cpp ../RemoteTarget.cpp

include $(LLVM_SRC_ROOT)/Makefile.rules
