##===- tools/extra/test/Unit/Makefile ----------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

CLANG_LEVEL := ../../..
include $(CLANG_LEVEL)/../../Makefile.config

PARALLEL_DIRS := clang-apply-replacements clang-modernize clang-query clang-tidy clang-rename

include $(CLANG_LEVEL)/Makefile
