# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Clang Tidy'

on:
  push:
    branches: [trunk, action-test]
  pull_request:

permissions:
  contents: read # For actions/checkout.
  pull-requests: read # For dorny/paths-filter to read pull requests.

# Cancel previous workflows on the PR when there are multiple fast commits.
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: ./.github/actions/test
        with:
          matrix_runner: 'ubuntu-22.04'
          matrix_build_mode: 'clang-tidy'
          head_sha: ${{ github.event.pull_request.head.sha }}
          base_sha:
            ${{ github.event_name == 'pull_request' &&
            github.event.pull_request.base.sha ||
            github.event.merge_group.base_sha }}
          remote_cache_upload: ${{ env.remote_cache_upload }}
          remote_cache_key: ${{ secrets.CARBON_BUILDS_GITHUB }}
