name: Issue Subscriber

on:
  issues:
    types:
      - labeled

jobs:
  auto-subscribe:
    runs-on: ubuntu-latest
    if: github.repository == 'llvm/llvm-project'
    steps:
    - name: Setup Automation Script
      run:  |
        curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/github-automation.py
        curl -O -L https://raw.githubusercontent.com/$GITHUB_REPOSITORY/$GITHUB_SHA/llvm/utils/git/requirements.txt
        chmod a+x github-automation.py
        pip install -r requirements.txt

    - name: Update watchers
      run: |
        ./github-automation.py \
          --token ${{ secrets.ISSUE_SUBSCRIBER_TOKEN }} \
          issue-subscriber \
          --issue-number ${{ github.event.issue.number }} \
          --label-name ${{ github.event.label.name }}
