---yaml
version: '3'

name: 'Auto label PRs'

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: &filters
            documentation:
              - '*.md'
              - 'docs/**'
            explorer:
              - 'explorer/**'
            infrastructure:
              - 'BUILD'
              - 'WORKSPACE'
              - '.*'
              - '.*/**'
              - 'bazel/**'
              - 'scripts/**'
            toolchain:
              - 'toolchain/**'

      - id: documentation
        if: steps.filter.outputs.docs == 'true'
        run: |
          gh pr edit "${PR}" --add-label "documentation"
        env:
          PR: ${{ github.event.pull_request.html_url }}

      - id: explorer
        if: steps.filter.outputs.explorer == 'true'
        run: |
          gh pr edit "${PR}" --add-label "explorer"
        env:
          PR: ${{ github.event.pull_request.html_url }}

      - id: infrastructure
        if: steps.filter.outputs.infrastructure == 'true'
        run: |
          gh pr edit "${PR}" --add-label "infrastructure"
        env:
          PR: ${{ github.event.pull_request.html_url }}

      - id: toolchain
        if: steps.filter.outputs.toolchain == 'true'
        run: |
          gh pr edit "${PR}" --add-label "toolchain"
        env:
          PR: ${{ github.event.pull_request.html_url }}
