# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: 'Auto label PRs'

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Filter files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            documentation:
              - '*.md'
              - 'docs/**'
            explorer:
              - 'explorer/**'
            infrastructure:
              - 'BUILD'
              - 'WORKSPACE'
              - '.*'
              - '.*/**'
              - 'bazel/**'
              - 'scripts/**'
            toolchain:
              - 'toolchain/**'

      - name: Add label - documentation
        if: steps.filter.outputs.docs == 'true'
        run: |
          gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "documentation"

      - name: Add label - explorer
        if: steps.filter.outputs.explorer == 'true'
        run: |
          gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "explorer"

      - name: Add label - infrastructure
        if: steps.filter.outputs.infrastructure == 'true'
        run: |
          gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "infrastructure"

      - name: Add label - toolchain
        if: steps.filter.outputs.toolchain == 'true'
        run: |
          gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "toolchain"
