# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Create PR suggestions based on problems found by pre-commit action.
name: pre-commit-suggestions

# This action is run whenever the `pre-commit` action finishes. Because the
# `pre-commit` action is an unprivileged action running on (for example) the
# `pull_request` event, it's run without write permissions to the repository, so
# we use a separate privileged `workflow_run` action here to pick up its results
# and convert them into suggestion comments.
#
# This action is only run from the workflow file on the trunk branch. Changes to
# this file will not take effect until they are merged to trunk.
on:
  workflow_run:
    workflows: [pre-commit]
    types:
      - completed

permissions:
  pull-requests: write

jobs:
  pull-request-suggestions:
    # Only generate suggestions if pre-commit for a PR failed.
    if: |
      ${{ github.event.workflow_run.conclusion == 'failure' }} &&
      ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download pre-commit output
        uses: actions/download-artifact@v4
        with:
          name: pre-commit output
          run-id: ${{ github.event.workflow_run.id }}

      # Use https://github.com/tido64/suggestion-bot to create PR suggestions
      # matching the diff that pre-commit created.
      - name: Create suggestions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GITHUB_EVENT_PATH=./event cat ./diff | \
          npx suggestion-bot -f -m "pre-commit checks made changes to the following files:"
