# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Tests (Windows)

on:
  push:
    branches: [trunk, action-test]
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group:
    '${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}'
  cancel-in-progress: true

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: block
          # prettier-ignore
          allowed-endpoints: >
            *.blob.storage.azure.net:443
            *.githubapp.com:443
            *.sourceforge.net:443
            api.github.com:443
            api.ipify.org:443
            bcr.bazel.build:443
            files.pythonhosted.org:443
            github.com:443
            go.dev:443
            mirror.bazel.build:443
            mirrors.kernel.org:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
            release-assets.githubusercontent.com:443
            releases.bazel.build:443
            storage.googleapis.com:443
            www.googleapis.com:443

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        with:
          filters: |
            has_code:
              - '!{**/*.md,LICENSE,CODEOWNERS,.git*}'

      - name: Cache LLVM and Clang installation
        if: steps.filter.outputs.has_code == 'true'
        id: cache-llvm-windows
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ~/llvm
          key: LLVM-19.1.7-Cache-windows-x64

      - name: Download LLVM and Clang installation
        if: >-
          steps.filter.outputs.has_code == 'true' &&
          steps.cache-llvm-windows.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $LLVM_RELEASE = "19.1.7"
          $LLVM_TARBALL = "clang+llvm-$LLVM_RELEASE-x86_64-pc-windows-msvc.tar.xz"
          $LLVM_PATH = "$HOME/llvm"
          Invoke-WebRequest "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_RELEASE/$LLVM_TARBALL" -OutFile $LLVM_TARBALL
          New-Item -ItemType Directory -Force -Path $LLVM_PATH
          tar -xJf $LLVM_TARBALL --strip-components=1 -C $LLVM_PATH
          Remove-Item $LLVM_TARBALL

      - name: Setup LLVM and Clang paths
        if: steps.filter.outputs.has_code == 'true'
        shell: pwsh
        run: |
          $LLVM_PATH = "$HOME/llvm"
          echo "$LLVM_PATH/bin" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "$LLVM_PATH/lib/clang/19/lib/windows" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Setup clang_rt bazelrc
        if: steps.filter.outputs.has_code == 'true'
        shell: pwsh
        run: |
          $clang_rt = "$env:USERPROFILE\llvm\lib\clang\19\lib\windows\clang_rt.builtins-x86_64.lib"
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc
          "build --linkopt=$($clang_rt -replace '\\', '/')" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=/FORCE:UNRESOLVED" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=/SUBSYSTEM:CONSOLE" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=/STACK:16777216" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=/FORCE:UNRESOLVED" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --features=-default_link_flags" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=-Xlinker" | Out-File -FilePath windows_clang_rt.bazelrc -Append
          "build --linkopt=/SUBSYSTEM:CONSOLE" | Out-File -FilePath windows_clang_rt.bazelrc -Append

      - name: Create dummy stack obj
        if: steps.filter.outputs.has_code == 'true'
        shell: pwsh
        run: |
          [IO.File]::WriteAllBytes("16777216.obj", [byte[]]@(0x64,0x86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))

      - name: Build and test common
        if: steps.filter.outputs.has_code == 'true'
        shell: pwsh
        run: |
          bazel --bazelrc=.bazelrc --bazelrc=windows_clang_rt.bazelrc test `
            //common:array_stack_test `
            //common:command_line_test `
            //common:emplace_by_calling_test `
            //common:enum_base_test `
            //common:enum_mask_base_test `
            //common:find_test `
            //common:growing_range_test `
            //common:hashing_test `
            //common:hashtable_key_context_test `
            //common:latch_test `
            //common:map_test `
            //common:raw_string_ostream_test `
            //common:set_test `
            //common:string_helpers_test `
            //common:struct_reflection_test `
            //common:template_string_test `
            --repo_env=CC=clang `
            --repo_env=CXX=clang++ `
            --force_pic=false `
            --copt=-fno-pic `
            --cxxopt=-fno-pic `
            --copt=-gz=none `
            --cxxopt=-gz=none `
            --copt=-Wno-unknown-attributes `
            --cxxopt=-Wno-unknown-attributes `
            "--@llvm-project//third-party:llvm_enable_zlib=false" `
            --features=archive_param_file `
            --test_output=errors
