# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# A convenience target for running the toolchain with the full prelude
# available.
alias(
    name = "carbon",
    actual = "//toolchain/install:prefix_root/bin/carbon",
)
